/**
 * STAT — Matcher + Notifier
 */

import { WATCH_GROUPS, ENVIRONMENTS, GHOST } from './config.js';
import { effectivePriority } from './fit.js';

// ─────────────────────────────────────────────────────────────────────────────
// KEYWORD MATCHER
// Returns { group, priority, label, matchedKw } or null
// ─────────────────────────────────────────────────────────────────────────────
export function matchJob(job, customKeywords = null) {
  // Include description in haystack so keywords buried in body text match.
  // Many Epic roles are titled "Application Analyst" with Epic in description only.
  const haystack = `${job.title} ${job.company} ${job.description || ''}`.toLowerCase();

  // CUSTOM KEYWORDS — profile-generated, highest priority
  // These are personalized to the stored resume (modules, certifications, target roles)
  // Generated by Gemini from the candidate profile, stored in StateStoreDO.
  if (customKeywords) {
    // Check exact phrases first (highest confidence)
    for (const kw of (customKeywords.exact || [])) {
      if (haystack.includes(kw.toLowerCase())) {
        return { group: WATCH_GROUPS[0], priority: 1, label: 'Epic · Profile Match', matchedKw: kw, source: 'profile' };
      }
    }
    // Check broad single words (good signal, lower confidence)
    for (const kw of (customKeywords.broad || [])) {
      if (haystack.includes(kw.toLowerCase())) {
        return { group: WATCH_GROUPS[0], priority: 1, label: 'Epic · Profile Match', matchedKw: kw, source: 'profile' };
      }
    }
    // Adjacent roles — P2 priority
    for (const kw of (customKeywords.adjacent || [])) {
      if (haystack.includes(kw.toLowerCase())) {
        return { group: WATCH_GROUPS[1], priority: 2, label: 'Adjacent · Profile Match', matchedKw: kw, source: 'profile' };
      }
    }
  }

  // STATIC KEYWORDS — fallback, covers gaps in profile-generated list
  for (const group of WATCH_GROUPS) {
    for (const kw of group.keywords) {
      if (haystack.includes(kw.toLowerCase())) {
        return { group, priority: group.priority, label: group.label, matchedKw: kw };
      }
    }
  }
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// ENVIRONMENT FILTER
// Returns true if the job passes the environment filter
// ─────────────────────────────────────────────────────────────────────────────
// ── Non-US location signals ───────────────────────────────────────────────────
// Country names and city patterns that confirm a non-US job.
// Conservative list: only suppress on unambiguous international signals.
// "Remote" with no location is always allowed (can't tell where from location alone).
// US territory names (Puerto Rico, Guam) are NOT excluded — US employers.
const NON_US_COUNTRIES = [
  // Europe
  'netherlands', 'amsterdam', 'united kingdom', 'england', 'scotland', 'wales',
  'london', 'manchester', 'germany', 'berlin', 'munich', 'france', 'paris',
  'spain', 'madrid', 'barcelona', 'italy', 'milan', 'rome', 'sweden', 'stockholm',
  'norway', 'oslo', 'denmark', 'copenhagen', 'finland', 'helsinki', 'switzerland',
  'zurich', 'geneva', 'austria', 'vienna', 'belgium', 'brussels', 'ireland', 'dublin',
  'poland', 'warsaw', 'portugal', 'lisbon', 'czech republic', 'prague', 'romania',
  'bucharest', 'hungary', 'budapest', 'slovakia', 'croatia', 'bulgaria', 'sofia',
  // Canada — common false positive for "remote US" postings
  'canada', 'ontario', 'toronto', 'british columbia', 'vancouver', 'alberta',
  'calgary', 'edmonton', 'quebec', 'montreal', 'manitoba', 'winnipeg',
  'nova scotia', 'new brunswick', 'saskatchewan',
  // Asia-Pacific
  'australia', 'sydney', 'melbourne', 'brisbane', 'perth', 'auckland',
  'new zealand', 'india', 'bangalore', 'bengaluru', 'mumbai', 'delhi', 'hyderabad',
  'pune', 'chennai', 'singapore', 'hong kong', 'japan', 'tokyo', 'osaka',
  'china', 'beijing', 'shanghai', 'south korea', 'seoul', 'taiwan', 'taipei',
  'philippines', 'manila', 'indonesia', 'jakarta', 'malaysia', 'kuala lumpur',
  'thailand', 'bangkok', 'vietnam', 'ho chi minh',
  // Latin America
  'mexico', 'mexico city', 'brazil', 'são paulo', 'sao paulo', 'rio de janeiro',
  'argentina', 'buenos aires', 'colombia', 'bogota', 'chile', 'santiago',
  'peru', 'lima', 'venezuela', 'ecuador', 'quito',
  // Middle East / Africa
  'united arab emirates', 'dubai', 'abu dhabi', 'saudi arabia', 'riyadh',
  'israel', 'tel aviv', 'turkey', 'istanbul', 'south africa', 'johannesburg',
  'cape town', 'nigeria', 'lagos', 'kenya', 'nairobi', 'egypt', 'cairo',
];

// ISO country codes that unambiguously indicate non-US (two-letter, used in jobhive CSV)
const NON_US_ISO = new Set([
  'GB','DE','FR','NL','CA','AU','IN','SG','JP','CN','KR','BR','MX','AR','CO',
  'CL','IE','SE','NO','DK','FI','CH','AT','BE','PL','PT','CZ','RO','HU','ES',
  'IT','NZ','ZA','NG','KE','EG','AE','SA','IL','TR','PH','ID','MY','TH','VN',
  'TW','HK',
]);

function isNonUsLocation(job) {
  // HiringCafe jobs have structured country/state data — most reliable
  if (job.hc) {
    const { workplaceStates, boundlessStates, isWorldwide } = job.hc;
    // Worldwide or no state list = could be US-eligible, don't reject
    if (isWorldwide || workplaceStates.length === 0) return false;
    // If ALL listed states are non-US country names (e.g. "United Kingdom, GB")
    const usStatePattern = /\b(Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming|DC|District of Columbia|Remote)\b/i;
    const hasUsState = workplaceStates.some(s => usStatePattern.test(s));
    if (!hasUsState && workplaceStates.length > 0 && workplaceStates.length <= 5) {
      return true; // Small explicit list with no US state = non-US
    }
    return false;
  }

  // countryIso field (from jobhive CSV or enriched jobs)
  if (job.countryIso && job.countryIso !== 'US' && job.countryIso !== 'USA') {
    if (NON_US_ISO.has(job.countryIso.toUpperCase())) return true;
  }

  // Location string analysis — last resort
  const loc = (job.location ?? '').toLowerCase().trim();
  if (!loc || loc === 'remote' || loc.includes('united states') || loc.includes('usa')) {
    return false; // No location, pure remote, or explicit US = pass
  }

  // Check for non-US country names in the location string
  if (NON_US_COUNTRIES.some(c => loc.includes(c))) return true;

  // "Remote - XX" or "XX, YY" where YY is a non-US 2-letter country code
  // e.g. "Amsterdam, NL" or "London, UK" or "Toronto, ON, CA"
  const countryCodeMatch = loc.match(/,\s*([a-z]{2})\s*$/);
  if (countryCodeMatch) {
    const code = countryCodeMatch[1].toUpperCase();
    if (NON_US_ISO.has(code)) return true;
  }

  return false;
}

export function passesEnvFilter(job) {
  // Geo gate: reject unambiguously non-US locations
  // Conservative — only suppresses on clear international signals.
  // Unknown/ambiguous locations (bare "Remote", no location) always pass.
  if (isNonUsLocation(job)) return false;

  // Environment gate: remote or hybrid only
  if (!ENVIRONMENTS || ENVIRONMENTS.length === 0) return true;
  if (!job.environment) return true; // unknown env — let through
  const envs = Array.isArray(ENVIRONMENTS) ? ENVIRONMENTS : [ENVIRONMENTS];
  return envs.some(e => job.environment.toLowerCase().includes(e.toLowerCase()));
}

// ─────────────────────────────────────────────────────────────────────────────
// GHOST AGE LABEL
// Returns a human-readable age string for inclusion in alerts
// ─────────────────────────────────────────────────────────────────────────────
export function ghostLabel(job) {
  if (!job.ghostFlag) return null;
  if (job.ghostFlag === 'suppress') return null; // caller should have filtered this
  // 'warn'
  return `⚠️ ${job.daysAgo}d old — verify still open`;
}

// ─────────────────────────────────────────────────────────────────────────────
// JOB URL LIVENESS CHECK
// HEAD request on the job's apply URL before alerting.
// Returns: 'live' | 'dead' | 'unknown'
//
// 'live'    — URL returned 200/301/302 → confirmed active, alert fires
// 'dead'    — URL returned 4xx → job removed from ATS, suppress alert,
//             do NOT add to seen-set (re-evaluates next poll in case transient)
// 'unknown' — fetch failed (timeout, network, 5xx) → let alert through with
//             a note; better to false-positive than silently drop a real match
//
// Why this beats HiringCafe: they confirm jobs at crawl time (up to 12hr ago).
// STAT confirms the URL is live at the moment the alert fires.
//
// Timeout: 4s — fast enough to not block the DO alarm loop, long enough for
// slow ATS endpoints (Taleo / Workday SSR can be sluggish).
// ─────────────────────────────────────────────────────────────────────────────
export async function checkJobLiveness(job) {
  if (!job.url) return 'unknown';

  // iCIMS sitemap-discovered jobs may have partial titles with no meaningful
  // detail URL yet — skip liveness check, treat as unknown
  if (job.atsSource === 'icims' && !job.title) return 'unknown';

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 4_000);

  try {
    // Use HEAD first — avoids downloading body, much faster
    const res = await fetch(job.url, {
      method: 'HEAD',
      signal: controller.signal,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
      },
      redirect: 'follow',
    });
    clearTimeout(timeout);

    if (res.status >= 400 && res.status < 500) return 'dead';
    if (res.status >= 200 && res.status < 400) return 'live';
    // 5xx, etc. → unknown
    return 'unknown';

  } catch (e) {
    clearTimeout(timeout);
    // AbortError = timeout; TypeError = network failure
    // Both → unknown (don't suppress, can't confirm either way)
    return 'unknown';
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// PUSHOVER NOTIFICATION
// priority: -2 silent | -1 quiet | 0 normal | 1 high (bypasses DnD) | 2 emergency
// ─────────────────────────────────────────────────────────────────────────────
export async function sendPushover(env, { title, message, url, urlTitle, priority }) {
  if (!env.PUSHOVER_APP_TOKEN || !env.PUSHOVER_USER_KEY) return;
  const body = new URLSearchParams({
    token:     env.PUSHOVER_APP_TOKEN,
    user:      env.PUSHOVER_USER_KEY,
    title:     title.slice(0, 250),
    message:   message.slice(0, 1024),
    url:       url ?? '',
    url_title: urlTitle ?? 'View Job',
    priority:  String(priority ?? 0),
    sound:     priority >= 1 ? 'siren' : 'pushover',
    ...(priority === 2 ? { retry: '60', expire: '3600' } : {}),
  });
  try {
    const res = await fetch('https://api.pushover.net/1/messages.json', {
      method: 'POST', body,
    });
    const data = await res.json();
    if (data.status !== 1) console.error('Pushover error:', JSON.stringify(data));
  } catch (e) { console.error('Pushover failed:', e.message); }
}

// ─────────────────────────────────────────────────────────────────────────────
// SENDGRID EMAIL
// ─────────────────────────────────────────────────────────────────────────────
export async function sendEmail(env, { subject, htmlBody }) {
  if (!env.RESEND_API_KEY || !env.ALERT_EMAIL) return;
  // Resend API — same service FIELD uses for night-owl and daily-brief emails.
  // Free tier: 3,000 emails/month, 100/day. From address locked to
  // onboarding@resend.dev on free tier (verify a domain for custom sender).
  const payload = {
    from:    'STAT Job Watcher <onboarding@resend.dev>',
    to:      [env.ALERT_EMAIL],
    subject,
    html:    htmlBody,
  };
  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${env.RESEND_API_KEY}`,
        'Content-Type':  'application/json',
      },
      body: JSON.stringify(payload),
    });
    if (!res.ok) console.error('Resend error:', res.status, await res.text());
  } catch (e) { console.error('Email failed:', e.message); }
}

// ─────────────────────────────────────────────────────────────────────────────
// EMAIL HTML BUILDER
// ─────────────────────────────────────────────────────────────────────────────
export function buildEmailHtml(newMatches) {
  const priorityColor = (p) => p === 1 ? '#dc2626' : p === 2 ? '#d97706' : '#16a34a';
  const priorityBg    = (p) => p === 1 ? '#fef2f2' : p === 2 ? '#fffbeb' : '#f0fdf4';

  const rows = newMatches.map(({ job, match }) => {
    const fitRow = (() => {
      if (job.fitScore == null) return '';
      const color = job.fitScore >= 8 ? '#16a34a' : job.fitScore >= 6 ? '#d97706' : '#dc2626';
      return `<div style="color:${color};font-size:12px;margin-top:4px;font-weight:600">Fit: ${job.fitScore}/10 — ${job.fitVerdict || ''}<span style="color:#64748b;font-weight:400"> · ${job.fitReasoning || ''}</span></div>`;
    })();
    const coverRow = (() => {
      if (!job.coverLetterOpener) return '';
      // Shown only when fit score >= 7 (Gemini returns null below that threshold)
      return `<div style="margin-top:10px;padding:10px 12px;background:#f8fafc;border-left:3px solid #cbd5e1;border-radius:0 4px 4px 0">
        <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#94a3b8;margin-bottom:4px">Cover Letter Opener</div>
        <div style="font-size:13px;color:#374151;line-height:1.5">${job.coverLetterOpener}</div>
      </div>`;
    })();
    const mdRow = (() => {
      if (!job.mdBadge) return '';
      const color = job.mdBadge.includes('likely')   ? '#1a6b6b'
                  : job.mdBadge.includes('possible') ? '#6b5200'
                  : '#8b2a2a';
      const bg    = job.mdBadge.includes('likely')   ? '#e8f4f4'
                  : job.mdBadge.includes('possible') ? '#faf5e8'
                  : '#f9eded';
      const detail = job.mdSignals?.length ? ` · ${job.mdSignals.join(', ')}` : '';
      return `<div style="color:${color};background:${bg};font-size:11px;margin-top:4px;padding:2px 8px;border-radius:3px;display:inline-block">${job.mdBadge}${detail}</div>`;
    })();
    const hcRow = (() => {
      if (!job.hc) return '';
      const parts = [];
      if (job.hc.seniorityLevel)      parts.push(job.hc.seniorityLevel);
      if (job.hc.minYoe != null)      parts.push(`${job.hc.minYoe}+ yrs`);
      if (job.hc.certifications?.length) parts.push(job.hc.certifications.slice(0,2).join(', '));
      if (job.hc.visaSponsorship)     parts.push('visa ok');
      if (job.hc.requirementsSummary) parts.push(
        `<span style="color:#7a6e5e;font-style:italic">${job.hc.requirementsSummary.slice(0,120)}</span>`
      );
      if (!parts.length) return '';
      return `<div style="font-size:11px;color:#64748b;margin-top:3px">${parts.join(' · ')}</div>`;
    })();
    const ghost = ghostLabel(job);
    const sal   = job.salary ? `<span style="color:#16a34a;font-weight:600">${job.salary}</span>` : '';
    const envBadge = job.environment
      ? `<span style="background:#e0f2fe;color:#0369a1;padding:2px 8px;border-radius:999px;font-size:11px;font-weight:700;text-transform:uppercase;margin-right:6px">${job.environment}</span>`
      : '';
    const pBadge = `<span style="background:${priorityBg(match.priority)};color:${priorityColor(match.priority)};padding:2px 8px;border-radius:999px;font-size:11px;font-weight:700;text-transform:uppercase">P${match.priority} · ${match.label}</span>`;
    const atsBadge = `<span style="background:#f1f5f9;color:#64748b;padding:2px 8px;border-radius:999px;font-size:10px;font-weight:600;text-transform:uppercase;margin-left:6px">${job.atsSource}</span>`;
    const ghostRow = ghost ? `<div style="color:#d97706;font-size:12px;margin-top:4px">${ghost}</div>` : '';
    const daysRow  = job.daysAgo !== null && !ghost
      ? `<div style="color:#94a3b8;font-size:11px;margin-top:2px">Posted ${job.daysAgo}d ago</div>` : '';
    const livenessRow = job.liveness === 'unknown'
      ? `<div style="color:#f59e0b;font-size:11px;margin-top:2px">⚡ URL unconfirmed — verify before applying</div>` : '';
    // Salary display — disclosed vs inferred, with transparency violation flag
    const salaryDisplay = (() => {
      if (job.transparencyViolation) {
        return `<div style="color:#8b2a2a;font-size:11px;margin-top:3px">⚠ No salary disclosed · legally required in ${job.transparencyFlag}</div>`;
      }
      if (!job.salary) return '';
      const inferredNote = job.salaryInferred && job.salaryLabel
        ? `<div style="color:#7a6e5e;font-size:10px;margin-top:1px;font-family:monospace">${job.salaryLabel}</div>`
        : '';
      const salaryColor = job.salaryInferred ? '#6b5200' : '#16a34a';
      const salaryPrefix = job.salaryInferred ? '~' : '';
      return `<div style="color:${salaryColor};font-weight:600;font-size:13px;margin-top:3px">${salaryPrefix}${job.salary}</div>${inferredNote}`;
    })();

    return `
      <tr style="border-bottom:1px solid #f0f0f0">
        <td style="padding:16px 0">
          <div style="margin-bottom:6px">${pBadge}${atsBadge}</div>
          <div style="font-size:17px;font-weight:700;margin-bottom:4px">
            <a href="${job.url}" style="color:#1a1a1a;text-decoration:none">${job.title}</a>
          </div>
          <div style="color:#555;font-size:14px;margin-bottom:4px">
            ${job.company}${job.location ? ` · ${job.location}` : ''}
          </div>
          <div style="margin-bottom:6px">${envBadge}</div>
          ${salaryDisplay}
          ${fitRow}
          ${coverRow}
          ${mdRow}
          ${hcRow}
          ${ghostRow}${daysRow}${livenessRow}
          <a href="${job.url}" style="display:inline-block;background:#111;color:#fff;padding:7px 16px;border-radius:6px;font-size:12px;font-weight:700;text-decoration:none;margin-top:8px">Apply Now →</a>
        </td>
      </tr>`;
  }).join('');

  const p1Count = newMatches.filter(m => m.match.priority === 1).length;
  const hsCount = newMatches.filter(m => m.match.label?.includes('Health System')).length;
  const consultCount = newMatches.filter(m => m.match.label?.includes('Consulting')).length;
  const headline = p1Count > 0
    ? `${p1Count} P1 match${p1Count > 1 ? 'es' : ''}${hsCount ? ` · ${hsCount} health system` : ''}${consultCount ? ` · ${consultCount} consulting` : ''}`
    : `${newMatches.length} new match${newMatches.length > 1 ? 'es' : ''}`;

  return `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:640px;margin:0 auto;background:#fff">
      <div style="background:#0f172a;color:#fff;padding:24px 28px">
        <div style="font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#64748b;margin-bottom:8px">STAT · Job Intelligence</div>
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px">${headline}</div>
        <div style="color:#94a3b8;font-size:13px;margin-top:4px">${new Date().toLocaleString('en-US', { timeZone: 'America/New_York' })} ET</div>
      </div>
      <div style="padding:0 28px">
        <table style="width:100%;border-collapse:collapse">${rows}</table>
      </div>
      <div style="padding:20px 28px;background:#f8fafc;color:#94a3b8;font-size:11px;margin-top:16px">
        STAT monitors ${newMatches[0]?.job?.atsSource ? 'direct ATS sources' : 'HiringCafe + direct ATS sources'} — all jobs confirmed live at the source.
      </div>
    </div>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// DISPATCH ALERTS for a batch of new matches
// Handles Pushover priority routing + email digest
// ─────────────────────────────────────────────────────────────────────────────
export async function dispatchAlerts(env, newMatches) {
  if (newMatches.length === 0) return;

  newMatches.sort((a, b) => a.match.priority - b.match.priority);

  const p1  = newMatches.filter(m => effectivePriority(m.match.priority, m.job.fitScore) === 1);
  const p2  = newMatches.filter(m => effectivePriority(m.match.priority, m.job.fitScore) === 2);
  const p3  = newMatches.filter(m => effectivePriority(m.match.priority, m.job.fitScore) >= 3);

  // P1: one push per job — HIGH priority, bypasses Do Not Disturb, siren sound
  for (const { job, match } of p1) {
    const sal = (() => {
      if (!job.salary) return '';
      const prefix = job.salaryInferred ? ' · ~' : ' · ';
      return `${prefix}${job.salary}`;
    })();
    const env2  = job.environment ? ` · ${job.environment}` : '';
    const ghost = ghostLabel(job);
    const ghostLine = ghost ? `\n${ghost}` : '';
    const unverLine = job.liveness === 'unknown' ? '\n⚡ URL unconfirmed — verify before applying' : '';
    const fitLine = job.fitScore != null ? `\nFit: ${job.fitScore}/10 — ${job.fitVerdict || ''}` : '';
    const mdLine  = job.mdBadge ? `\n${job.mdBadge}` : '';
    await sendPushover(env, {
      title:    `🚨 STAT P1: ${match.label}`,
      message:  `${job.title}\n${job.company}${job.location ? ' · ' + job.location : ''}${env2}${sal}${fitLine}${mdLine}${ghostLine}${unverLine}`,
      url:      job.url,
      urlTitle: 'Apply Now',
      priority: 1,
    });
  }

  // P2: single batched push — normal priority (Product/Data/Analytics)
  if (p2.length > 0) {
    const lines = p2
      .map(({ job, match }) => {
        const ghost = ghostLabel(job);
        const fitNote = job.fitScore != null ? ` [${job.fitScore}/10]` : '';
        return `[P2] ${job.title} @ ${job.company}${fitNote}${ghost ? ' ' + ghost : ''}`;
      })
      .join('\n');
    await sendPushover(env, {
      title:    `📋 STAT P2: ${p2.length} match${p2.length > 1 ? 'es' : ''}`,
      message:  lines,
      url:      'https://hiring.cafe',
      urlTitle: 'Open HiringCafe',
      priority: 0,
    });
  }

  // P3: email only — no Pushover (Product / Project / IT roles)
  // These are lower-signal matches. A push notification would be noise.

  // Email: one digest for all matches (P1 + P2 + P3)
  await sendEmail(env, {
    subject:  `[STAT] ${newMatches.length} new match${newMatches.length > 1 ? 'es' : ''} — ${newMatches[0].job.title} @ ${newMatches[0].job.company}`,
    htmlBody: buildEmailHtml(newMatches),
  });
}
